# Generated by Django 3.2.7 on 2021-09-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveSmallIntegerField(blank=True)),
                ('favorite', models.CharField(blank=True, max_length=1000)),
                ('introduce', models.TextField(blank=True)),
            ],
        ),
    ]
