# Generated by Django 3.2.7 on 2021-09-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_infoadminuser_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoAdminUser',
            new_name='InfoAdmin',
        ),
    ]
