# Generated by Django 3.2.7 on 2021-09-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210919_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoadminuser',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
